version: '3'

services:
    go-api-service:
        build: ./project-go-api
        volumes: 
            - ./project-go-api:/usr/src/app
        ports:
            - 5000:80
    sensors-service:
        build: ./project-sensors
        volumes: 
            - ./project-sensors:/usr/src/app
        ports:
            - 5001:80
        devices: 
            - /dev/gpiomem:/dev/gpiomem
        privileged: true