version: '3'

services:
    go-service:
        build: ./project-go-api/src/github.com.michaeljohnwatters.project.go.api
        ports:
            - 5000:8080
    sensors-service:
        build: ./project-sensors
        volumes: 
            - ./project-sensors:/usr/src/app
        ports:
            - 5001:80
        devices: 
            - /dev/gpiomem:/dev/gpiomem
        privileged: true
    website-service:
        build: .
        ports:
            - 5002:8080